"""Generate a standalone Python script that reproduces all dataset transformations."""

import os
from typing import Any, Dict, List, Optional


def generate_script(events: List[Dict[str, Any]], output_path: Optional[str] = None) -> str:
    """Build a runnable Python script from audit events.

    Args:
        events: The ``AuditLogger.events`` list.
        output_path: If given, write the script to this file path.

    Returns:
        The generated script as a string.
    """
    resolved = _resolve_events(events)
    parts: List[str] = []

    load_ev = next((e for e in resolved if e["event"] == "load"), None)
    export_ev = next((e for e in reversed(resolved) if e["event"] == "export"), None)

    parts.append(_emit_header(load_ev, export_ev))

    step = 1
    for ev in resolved:
        etype = ev["event"]
        if etype == "load":
            parts.append(_emit_load(ev, step))
            step += 1
        elif etype == "operation":
            op = ev.get("operation", "")
            if op == "missing_values":
                parts.append(_emit_missing_values(ev, step))
            elif op == "outlier_remediation":
                parts.append(_emit_outlier_remediation(ev, step))
            step += 1
        elif etype == "export":
            parts.append(_emit_export(ev, step))
            step += 1

    script = "\n".join(parts) + "\n"

    if output_path:
        dirpath = os.path.dirname(output_path)
        if dirpath:
            os.makedirs(dirpath, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(script)

    return script


# ------------------------------------------------------------------
# Undo resolution
# ------------------------------------------------------------------

def _resolve_events(events: List[Dict]) -> List[Dict]:
    """Walk events and remove operations that were undone."""
    result: List[Optional[Dict]] = []
    ops_stack: List[int] = []  # indices of operation events in result

    for ev in events:
        if ev["event"] == "undo":
            if ops_stack:
                idx = ops_stack.pop()
                result[idx] = None
        else:
            result.append(ev)
            if ev["event"] == "operation":
                ops_stack.append(len(result) - 1)

    return [e for e in result if e is not None]


# ------------------------------------------------------------------
# Detail normalisation helpers
# ------------------------------------------------------------------

def _normalize_detail(value: Any) -> Dict[str, Any]:
    """Accept both old string format and new dict format."""
    if isinstance(value, str):
        return {"strategy": value}
    if isinstance(value, dict):
        return value
    return {"strategy": str(value)}


def _repr_value(val: Any) -> str:
    """Return a Python literal for *val*."""
    if isinstance(val, str):
        return repr(val)
    if isinstance(val, float):
        return repr(val)
    if isinstance(val, int):
        return repr(val)
    return repr(val)


# ------------------------------------------------------------------
# Emitters
# ------------------------------------------------------------------

def _emit_header(load_ev: Optional[Dict], export_ev: Optional[Dict]) -> str:
    source_name = "unknown"
    if load_ev:
        src = load_ev.get("source", {})
        source_name = src.get("filename") or src.get("table_name") or src.get("path", "unknown")
    ts = ""
    if export_ev:
        ts = export_ev.get("timestamp", "")

    return (
        '#!/usr/bin/env python3\n'
        '"""Reproduction script generated by Data Wizard.\n'
        '\n'
        'Replays all transformations applied during the cleaning session.\n'
        f'Original source: {source_name}\n'
        f'Generated: {ts}\n'
        '"""\n'
        '\n'
        'import sys\n'
        'import os\n'
        '\n'
        'import pandas as pd\n'
        'import numpy as np\n'
    )


def _emit_load(ev: Dict, step: int) -> str:
    src = ev.get("source", {})
    file_type = src.get("file_type", "CSV")
    path = src.get("path", "input_data.csv")
    lines: List[str] = []

    lines.append(f"\n# {'=' * 50}")
    lines.append(f"# Step {step}: Load data")
    lines.append(f"# {'=' * 50}")

    # Database source — emit skeleton
    if src.get("type") == "database":
        table = src.get("table_name", "table")
        lines.append(f"# Original source: database table '{table}'")
        lines.append("# TODO: fill in your database connection string")
        lines.append("# from sqlalchemy import create_engine")
        lines.append('# engine = create_engine("postgresql://user:pass@host/db")')
        lines.append(f'# df = pd.read_sql_table("{table}", engine)')
        lines.append(f'raise NotImplementedError("Database replay requires a connection string — see comments above")')
        return "\n".join(lines)

    # File source
    escaped_path = path.replace("\\", "\\\\")
    lines.append(f'INPUT_PATH = r"{path}"')
    lines.append("if len(sys.argv) > 1:")
    lines.append("    INPUT_PATH = sys.argv[1]")
    lines.append("")

    if file_type == "CSV":
        encoding = src.get("encoding", "utf-8")
        lines.append(f'df = pd.read_csv(INPUT_PATH, encoding="{encoding}", low_memory=False)')
    elif file_type == "TSV":
        encoding = src.get("encoding", "utf-8")
        lines.append(f'df = pd.read_csv(INPUT_PATH, sep="\\t", encoding="{encoding}", low_memory=False)')
    elif file_type == "Excel":
        sheet = src.get("sheet_name", 0)
        sheet_arg = repr(sheet)
        lines.append(f"df = pd.read_excel(INPUT_PATH, sheet_name={sheet_arg}, engine=\"openpyxl\")")
    elif file_type == "JSON":
        lines.append("df = pd.read_json(INPUT_PATH)")
    elif file_type == "Parquet":
        lines.append("df = pd.read_parquet(INPUT_PATH)")
    else:
        lines.append(f'df = pd.read_csv(INPUT_PATH)  # fallback for type "{file_type}"')

    lines.append('print(f"Loaded {len(df):,} rows x {len(df.columns)} cols from {INPUT_PATH}")')
    return "\n".join(lines)


def _emit_missing_values(ev: Dict, step: int) -> str:
    details = ev.get("details", {})
    lines: List[str] = []

    lines.append(f"\n# {'=' * 50}")
    lines.append(f"# Step {step}: Handle missing values")
    lines.append(f"# {'=' * 50}")

    for col, raw in details.items():
        cfg = _normalize_detail(raw)
        strategy = cfg.get("strategy", "leave")
        custom_value = cfg.get("custom_value")
        safe_col = repr(col)

        if strategy == "leave":
            continue

        lines.append(f"\n# Column {safe_col}: {strategy}")

        if strategy == "drop_rows":
            lines.append(f"df = df.dropna(subset=[{safe_col}]).reset_index(drop=True)")

        elif strategy == "fill_mean":
            lines.append(f"df[{safe_col}] = df[{safe_col}].fillna(df[{safe_col}].mean())")

        elif strategy == "fill_median":
            lines.append(f"df[{safe_col}] = df[{safe_col}].fillna(df[{safe_col}].median())")

        elif strategy == "fill_mode":
            lines.append(f"_mode = df[{safe_col}].mode()")
            lines.append(f"if len(_mode) > 0:")
            lines.append(f"    df[{safe_col}] = df[{safe_col}].fillna(_mode.iloc[0])")

        elif strategy == "fill_custom":
            val_repr = _repr_value(custom_value) if custom_value is not None else "None"
            lines.append(f"df[{safe_col}] = df[{safe_col}].fillna({val_repr})")

        elif strategy == "fill_forward":
            lines.append(f"df[{safe_col}] = df[{safe_col}].ffill()")

        elif strategy == "fill_backward":
            lines.append(f"df[{safe_col}] = df[{safe_col}].bfill()")

        elif strategy == "interpolate":
            lines.append(f"df[{safe_col}] = pd.to_numeric(df[{safe_col}], errors=\"coerce\").interpolate(method=\"linear\")")

    lines.append(f'\nprint(f"After missing-value handling: {{len(df):,}} rows x {{len(df.columns)}} cols")')
    return "\n".join(lines)


def _emit_outlier_remediation(ev: Dict, step: int) -> str:
    details = ev.get("details", {})
    lines: List[str] = []

    lines.append(f"\n# {'=' * 50}")
    lines.append(f"# Step {step}: Outlier remediation")
    lines.append(f"# {'=' * 50}")

    for col, raw in details.items():
        cfg = _normalize_detail(raw)
        strategy = cfg.get("strategy", "leave")
        method = cfg.get("method", "iqr")
        threshold = cfg.get("threshold")
        safe_col = repr(col)

        if strategy == "leave":
            continue

        lines.append(f"\n# Column {safe_col}: {strategy} (method={method}, threshold={threshold})")

        # Emit bounds / mask computation
        if method == "zscore":
            if threshold is None:
                threshold = 3.0
            lines.append(f"_mean = df[{safe_col}].mean()")
            lines.append(f"_std = df[{safe_col}].std()")
            lines.append(f"_lower = _mean - {threshold} * _std")
            lines.append(f"_upper = _mean + {threshold} * _std")
            lines.append(f"_z = np.abs((df[{safe_col}] - _mean) / _std)")
            lines.append(f"_mask = _z > {threshold}")
        else:  # iqr
            if threshold is None:
                threshold = 1.5
            lines.append(f"_q1 = df[{safe_col}].quantile(0.25)")
            lines.append(f"_q3 = df[{safe_col}].quantile(0.75)")
            lines.append(f"_iqr = _q3 - _q1")
            lines.append(f"_lower = _q1 - {threshold} * _iqr")
            lines.append(f"_upper = _q3 + {threshold} * _iqr")
            lines.append(f"_mask = (df[{safe_col}] < _lower) | (df[{safe_col}] > _upper)")

        # Emit remediation
        if strategy == "remove":
            lines.append(f"df = df[~_mask].reset_index(drop=True)")

        elif strategy == "cap":
            lines.append(f"df.loc[df[{safe_col}] < _lower, {safe_col}] = _lower")
            lines.append(f"df.loc[df[{safe_col}] > _upper, {safe_col}] = _upper")

        elif strategy == "log":
            lines.append(f"_col_min = df[{safe_col}].min()")
            lines.append(f"if _col_min <= 0:")
            lines.append(f"    _shift = abs(_col_min) + 1")
            lines.append(f"    df[{safe_col}] = np.log1p(df[{safe_col}] + _shift)")
            lines.append(f"else:")
            lines.append(f"    df[{safe_col}] = np.log1p(df[{safe_col}])")

    lines.append(f'\nprint(f"After outlier remediation: {{len(df):,}} rows x {{len(df.columns)}} cols")')
    return "\n".join(lines)


def _emit_export(ev: Dict, step: int) -> str:
    dest = ev.get("destination", "output.csv")
    fmt = ev.get("format", "csv")
    lines: List[str] = []

    lines.append(f"\n# {'=' * 50}")
    lines.append(f"# Step {step}: Export")
    lines.append(f"# {'=' * 50}")

    if fmt == "database":
        table = ev.get("extra", {}).get("table_name", "exported_data")
        lines.append(f"# Original export: database table '{table}'")
        lines.append("# TODO: fill in your database connection string")
        lines.append(f'# engine = create_engine("postgresql://user:pass@host/db")')
        lines.append(f'# df.to_sql("{table}", engine, if_exists="replace", index=False)')
        lines.append(f'print(f"Script complete: {{len(df):,}} rows x {{len(df.columns)}} cols (DB export skipped)")')
        return "\n".join(lines)

    lines.append(f'OUTPUT_PATH = r"{dest}"')
    lines.append("if len(sys.argv) > 2:")
    lines.append("    OUTPUT_PATH = sys.argv[2]")
    lines.append("")

    if fmt == "csv":
        lines.append("df.to_csv(OUTPUT_PATH, index=False)")
    elif fmt == "excel":
        lines.append('df.to_excel(OUTPUT_PATH, index=False, engine="openpyxl")')
    elif fmt == "json":
        lines.append('df.to_json(OUTPUT_PATH, orient="records", indent=2)')
    elif fmt == "parquet":
        lines.append("df.to_parquet(OUTPUT_PATH, index=False)")
    elif fmt in ("tsv", "tab"):
        lines.append('df.to_csv(OUTPUT_PATH, sep="\\t", index=False)')
    else:
        lines.append(f"df.to_csv(OUTPUT_PATH, index=False)  # fallback for format '{fmt}'")

    lines.append(f'print(f"Exported {{len(df):,}} rows x {{len(df.columns)}} cols to {{OUTPUT_PATH}}")')
    return "\n".join(lines)
